### ISSUE TITLE
Implement message logic within channels

### ISSUE THREAD

**Issue by BSchoolland** [Opperating-Owls/operating-owls-business-communication-platform-refactor#13]
## Desired Feature
Copy over the text channel logic, messages, and message editing popup.
## Tasks
- [ ] Create or locate a Text Channel component
- [ ] Copy over logic from old repo.
- [ ] Ensure Outlets are still being used correctly

## Additional context
Figma:
![image](https://github.com/Opperating-Owls/operating-owls-business-communication-platform-refactor/assets/95189424/3e17d467-2af7-4a05-b9c4-3c4f87a5ec6e)
Original Repo:
![image](https://github.com/Opperating-Owls/operating-owls-business-communication-platform-refactor/assets/95189424/12712ccf-9755-46d3-83d6-fe46b305f903)
