### ISSUE TITLE
Firebase Data Structure

### ISSUE THREAD

**Issue by BSchoolland** [Opperating-Owls/operating-owls-business-communication-platform-refactor#2]
## Description
Create the firebase data structure with some sample data
## Tasks
- [ ] users: Contains user data, and what servers the user is in.
- [ ] servers: Contains server data, all members, member permissions, permission levels, and all channels
- [ ] Channels: Message link array, Permission settings
- [ ] Messages: Which channel they are a part of, user that sent it, message content, deleted true/false

**Comment by BSchoolland** [comment]
This is going to be removed in favor of a dedicated backend
